name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby enviornment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Setup Node.js enviornemnt
        uses: actions/setup-node@v1.4.3

      - name: Install yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update && sudo apt install yarn
          yarn --version

      - name: Install all dependencies
        run: |
          cd website && bundle install && cd ..
          yarn

      - name: Build assets with gulp
        run: gulp

      - name: Build site with Jekyll
        run: cd website && exec jekyll build && cd ..
    
      - name: Prepare
        run: |
          mkdir public
          cp -r website/_site/* public
          cd public
          cd ..

      - name: Save as an artifact
        uses: actions/upload-artifact@master
        with:
          name: public-website
          path: ./public 
  
  security-testing:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: public-website
          path: ./public 

      - name: Setup Node.js enviornemnt
        uses: actions/setup-node@v1.4.3
      
      - name: Install http-server
        run: sudo npm install --global http-server
        
      - name: Run http-server
        run: http-server ./public &
      
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: http://localhost:8080
          cmd_options: -I  
      

  deploy:
    runs-on: ubuntu-latest
    needs:
      - security-testing
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: public-website
          path: ./public  

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
